### ISSUE TITLE
[META] Migration progress

### ISSUE THREAD

**Issue by saschaeggi** [backdrop-contrib/gin#36]
This is a META issue to document the current state of the migration work. Please note that currently the experience is very buggy as we have just started porting things over to Backdrop.

The following features have been already been ported or known to be needed:

- Gin settings
  - [x] https://github.com/backdrop-contrib/gin/issues/97
  - [x] https://github.com/backdrop-contrib/gin/issues/7
  - [x] https://github.com/backdrop-contrib/gin/issues/19
  - [x] Darkmode
  - [x] Accent color
  - [x] Focus color
  - [x] Increase contrast
  - [x] Layout density
- [x] Admin Bar (part one - horizontal)
- [x] Sticky header
- [x] CKEditor
- [x] Boolean Toggle
- [x] https://github.com/backdrop-contrib/gin/issues/20
- [x] https://github.com/backdrop-contrib/gin/issues/21
- [x] https://github.com/backdrop-contrib/gin/issues/31
- [x] https://github.com/backdrop-contrib/gin/issues/50

**Comment by laryn** [comment]
Thanks @saschaeggi! I'm still largely away from the computer (on vacation) for a few more weeks but will be around more regularly again after that...

**Comment by laryn** [comment]
@saschaeggi I took the liberty of beginning to turn this meta into a list of completed and yet-to-complete items. It's obviously not exhaustive and we can edit/modify as we go. Sound okay?

**Comment by laryn** [comment]
Closing this meta issue as the basic elements are complete. Anything else will become a new issue from here on out.
